server:
  port: 8080

spring:
  config:
    import: optional:application-secret.yml

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url:
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true