name: Build Only

on:
  pull_request:
    branches: [ main ]  # PR 대상이 main일 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 빌드
      - name: Run Gradle Build
        run: ./gradlew clean build